Sprint 3
Alkamenos/middle.messenger.praktikum.yandex pull request #5
Opened 2021-08-19 04:24 UTC by Alkamenos

2021-08-20 07:05 UTC, nickchamel requested changes
Привет. Спасибо за работу! Отписал тебе рекомендации в комментариях, но работа пока недоделана, вынужден вернуть.
### Что НЕ сделано по заданиям:
![image](https://user-images.githubusercontent.com/28347933/130193609-3a99a15f-cc6c-431a-822d-c3c7905738fe.png)
![image](https://user-images.githubusercontent.com/28347933/130193743-c9e49dd0-1e5a-45ec-beae-56ef438e3f19.png)
У тебя сейчас просто как буд-то бы второй спринт.
Плюс сразу отмечу момент про валидацию на формах - у тебя сейчас только у одного филда выпадает ошибка, по заданию они должны выпадать быть на всех филдах на фокусе/блюре каждого, и еще раз при общем сабмите формы

2021-08-20 08:23 UTC, Alkamenos commented on src/components/Input/FormInput.ts
> +`;
это же pug он понимает только стиль описанный в его документации

2021-08-20 08:24 UTC, Alkamenos commented on src/components/Input/FormInput.ts
> +                }: IComponentProps) {
это просто автоформатирование в webstorm каких-либо гайдов по стилю кода как и что должно быть у нас нет

2021-08-20 08:25 UTC, Alkamenos commented on src/components/Input/FormInput.ts
> +        this.setProps({attributes: Object.assign(this.props.attributes, attributes)})
да, я тут немного запутался, сейчас подумаю как это лучше сделать, спасибо что обратил внимание

2021-08-20 08:27 UTC, Alkamenos commented on src/components/Input/Input.ts
> +const template = ``;
если компонент состоит из одного тега, т.е. не содердит внутри себя разметки, темплейт будет пустой  - да, а в коде я это сохранил чтобы сохранить единный стиль и в будущем легче добавлять например подсказку под input

2021-08-20 08:27 UTC, Alkamenos commented on src/components/MessageForm/MessageForm.scss
> +  box-shadow: 0 -6px 20px 4px #1e1e1eb0;
да, по невнимательности пропустил

2021-08-20 08:29 UTC, Alkamenos commented on src/index.ts
> +// })
понятно комментарии никто не любит, но я ожидал что ревью будет более глубокое и полезное для меня как разработчика

2021-08-20 08:29 UTC, Alkamenos commented on src/pages/ChatPage/ChatPage.ts
> +}
откуда эта информация?

2021-08-20 08:57 UTC, Alkamenos commented on src/components/Button/Button.ts
> +import clsx from 'clsx';
да без проблем, могу настроить в вебшторме, требований просто таких не было

2021-08-20 08:59 UTC, Alkamenos commented on src/services/http.ts
> +            }
хорошая идея спасибо

2021-08-20 09:53 UTC, nickchamel commented on src/components/Button/Button.ts
> +import clsx from 'clsx';
Дружище,
> Отписал тебе рекомендации в комментариях

Это все рекомендации как можно писать лучше, исходя из личного опыта на реальных боевых проектах и опыта коллег. Ты волен не исправлять то, что тебе прокомментируют, если конечно это не критичный момент.
У тебя критичных моментов 3:
- Мутация this.props
- Не везде есть обработка ошибок
- Функционал
Про последнее - лучше будет, если ты сфокусируешься на самом задании, потому что, как я уже сказал, работа как бы "застряла" во 2 спринте и много чего из 3 спринта просто не работает сейчас.

2021-08-20 12:04 UTC, Alkamenos commented on src/components/Button/Button.ts
> +import clsx from 'clsx';
Спасибо) Хотелось бы все-же подробнее. А то много чего не работает не очень понятно. Роутер есть, запросы есть, вебсокеты есть, тесты есть. Что ещё нужно?

2021-08-20 12:47 UTC, nickchamel commented on src/components/Button/Button.ts
> +import clsx from 'clsx';
Если сейчас это все есть хорошо - оправляй работу на ревью. (на момент отправки моего сообщения на нетлифай был старый деплой)

2021-08-20 12:51 UTC, Alkamenos commented on src/components/Button/Button.ts
> +import clsx from 'clsx';
поправлю твои замечания по коду и отправлю, примерно мин 30-40 еще

2021-08-20 12:52 UTC, nickchamel commented on src/components/Button/Button.ts
> +import clsx from 'clsx';
можешь сразу это исправить, на регистрации тоже самое
![image](https://user-images.githubusercontent.com/28347933/130236033-0c6d8655-f50f-4809-9beb-0fc81302c299.png)

2021-08-20 12:54 UTC, nickchamel commented on src/components/Button/Button.ts
> +import clsx from 'clsx';
И да, про валидацию на формах - это тоже критичный момент. Об этом написано в задании 2 спринта

2021-08-20 13:05 UTC, nickchamel commented on src/components/Button/Button.ts
> +import clsx from 'clsx';
> Спасибо) Хотелось бы все-же подробнее. А то много чего не работает не очень понятно. Роутер есть, запросы есть, вебсокеты есть, тесты есть. Что ещё нужно?

Просто оставлю это здесь
![image](https://user-images.githubusercontent.com/28347933/130237454-a6637929-a01f-4e85-bc6d-1ebef81237c3.png)

2021-08-21 13:33 UTC, nickchamel requested changes
Хорошо. Но еще остаются недоработки по заданиям, работу пока возвращаю.
По заданиям:
1. После отправки сообщения в чат, текстовое поле не очищается
2. Добавленные сообщения не появляются в чате после перезагрузки приложения
3. Кнопка настроек кликабельна, только после клика на чат
4. Невозможно обновить профиль (видимо не та регулярка на поле емейла)
![image](https://user-images.githubusercontent.com/28347933/130323245-3cf3097c-8966-486e-81cc-fe0b6d81c72f.png)
5. Не работает перезагрузка страниц
![image](https://user-images.githubusercontent.com/28347933/130323301-5535e5ca-d4d0-4de9-8a3c-48719ccd8a39.png)
6. После успешного логина запрос зацикливается и редиректа не происходит
![image](https://user-images.githubusercontent.com/28347933/130323108-7f866211-7559-4dcc-a8ca-3aff9e299926.png)
Так же советую обратить внимание на дубликаты запросов в остальных частях приложения
![image](https://user-images.githubusercontent.com/28347933/130323121-20de6aa2-90e7-4b7a-aa71-a0d8a4bd978d.png)

2021-08-21 13:33 UTC, nickchamel commented on src/pages/RegistrationPage/RegistrationPage.ts
> +                        }
Привязываться к описанию ошибки - плохая практика.
Оно в любой момент может поменяться - приложение может попросту перестать работать должным образом.
На самом деле checkAuth, который ты сделал в index.ts достаточно - если кука есть и она валидна - значит получили юзера и работаем, если что-то не так с кукой - значит редирект на логин.
Единственное это момент, если пользователь залогинен и находится в мессенджере например и сам введет в урле /login. Чтобы предотвратить это можно "закрывать" роуты, относительно текущего юзера, в роутере смотреть, есть он или нет, если есть и все ок с ним значит не делать переход и перерисовку

2021-08-21 15:38 UTC, nickchamel commented
Это задание все же нужно сделать
![image](https://user-images.githubusercontent.com/28347933/130327135-89ce9436-41fb-4cf3-bde3-53a234f40c49.png)
![image](https://user-images.githubusercontent.com/28347933/130327151-a571c3fb-bff9-4b79-b047-fc55f00a3ac8.png)
И обращаю внимание на то, что сообщения в чатах у тебя снизу вверху (последние наверху), а при добавлении последнее добавляется вниз

2021-08-21 16:06 UTC, Alkamenos commented
это какие-то настройки самого Netlify локально все работает

2021-08-23 16:55 UTC, merged